name: Deploy to Azure App Service

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm ci --legacy-peer-deps

      - name: Build Next.js app
        run: npm run build
        env:
          NODE_ENV: production
          AZURE_STORAGE_ACCOUNT_NAME: ${{ secrets.AZURE_STORAGE_ACCOUNT_NAME }}
          AZURE_STORAGE_ACCOUNT_KEY: ${{ secrets.AZURE_STORAGE_ACCOUNT_KEY }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}

      - name: Create deployment package
        run: |
          # Create a clean deployment package for Linux App Service
          mkdir deploy
          cp -r .next deploy/
          cp -r public deploy/
          cp package.json deploy/
          cp package-lock.json deploy/
          cp next.config.* deploy/ 2>/dev/null || true

          # Copy app directory if it exists
          if [ -d "app" ]; then
            cp -r app deploy/
          fi

          # Copy src directory if it exists
          if [ -d "src" ]; then
            cp -r src deploy/
          fi

          echo "Deployment package contents:"
          ls -la deploy/
          echo "Package size:"
          du -sh deploy/

      - name: Deploy to Azure App Service
        uses: azure/webapps-deploy@v1
        with:
          app-name: "h2all-m1-proto" # Your App Service name
          slot-name: "production"
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: "./deploy"
